spring:
  datasource:
    url: ${DB-URL:jdbc:mariadb://localhost:3300/demo?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB-NAME:root}
    password: ${DB-PASSWORD:dongcci}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

  oauth:
    kakao:
      client-id: b8da5111ad5fb989de71ae153b1bb0c9
      url:
        auth: https://kauth.kakao.com
        api: https://kapi.kakao.com

  data:
    redis:
      port: 6380
      host: localhost
      password:

server:
  port: 8081

jwt:
  secret: GaXmsBiD6L1Z2M3NorAExZp8gr3uPXDR6J6iZxe4pfYKTf0SV1+I0xGqmuPG+nmLVCl9/2+lYB/VFI+AgoFGpg==